// Code generated by "stringer -type=itemType"; DO NOT EDIT

package main

import "fmt"

const _itemType_name = "itemErroritemDotitemEOFitemClassitemExtendsitemOpenBraceitemCloseBraceitemFuncitemTextitemLeftDelimitemRightDelimitemFuncBodyitemFuncParamsitemMemberitemCommentitemLineComment"

var _itemType_index = [...]uint8{0, 9, 16, 23, 32, 43, 56, 70, 78, 86, 99, 113, 125, 139, 149, 160, 175}

func (i itemType) String() string {
	if i < 0 || i >= itemType(len(_itemType_index)-1) {
		return fmt.Sprintf("itemType(%d)", i)
	}
	return _itemType_name[_itemType_index[i]:_itemType_index[i+1]]
}
